### ISSUE TITLE
Exit code from wkhtmltopdf is too eager

### ISSUE THREAD

**Issue by dbfx** [cangelis/l4pdf#1]
Had a bit of an issue today where l4pdf was constantly refusing to give back a pdf. Tracked it down to an exit code of 1 from wkhtmltopdf; the reason however is a bit interesting -- 

```
# wkhtmltopdf 5424552c6da9e465e9.html ./test.pdf
Loading pages (1/6)
QSslSocket: cannot resolve SSLv2_client_method               ] 10%
QSslSocket: cannot resolve SSLv2_server_method
Warning: Failed to load file://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css (ignore)
Warning: Failed to load file://d1l6p2sc9645hc.cloudfront.net/tracker.js (ignore)
Warning: A finished ResourceObject received a loading progress signal. This migth be an indication of an iframe taking to long to load.
Warning: A finished ResourceObject received a loading finished signal. This migth be an indication of an iframe taking to long to load.
Counting pages (2/6)
Loading TOC (3/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to http error: 1005
```

Essentially it's errorring out because of random css/js on a page (pretty typical css+jss I should say).

If that's what error code 1 means, it might be a good idea to only error on > 1 ?

**Comment by cangelis** [comment]
Error code 1 means, there was an error while creating the PDF. You might want to take a look at this: https://github.com/antialize/wkhtmltopdf/blob/9e8b488df43403782162a834fb219584d0dc58d4/src/lib/utilities.cc

Is PDF file still generated even if wkhtmltopdf returns 1 ?

On the other hand you might want to take a look at your css and js URLs because it is trying searching in your file system instead of going to url. You may be forgetting `http://`

**Comment by dbfx** [comment]
Ye the PDF is still generated and it's perfect.

I agree completely with you about the CSS and JS but it's pretty common to have those types of rules. What it is is when you link to something like this -- 

```
script src="//test.com/test.js"
```

The problem is that's basically the standard way that most sites are including libraries like fonts, jquery, etc. If I guessed I would say at least half of sites might give this type of error.

I've added an "override" for it, but I opened the ticket to discuss what might be the best way to override it as when I do a composer update it's gonna go :)

**Comment by cangelis** [comment]
Do you have any idea what we can do in php-side? I think you can report this bug to [wkhtmltopdf repo](https://code.google.com/p/wkhtmltopdf/issues/list) or try compiling the latest source.

**Comment by cangelis** [comment]
I am closing this issue since doesn't look like l4pdf related. If you find anything we can do, please open it again.

**Comment by jorgelimafeitosa** [comment]
Someone found a fix for this? For the first try when I execute the WKHTMLTOIMAGE the data returns null, but when I execute for the second time, then the image returns, but no 100% equal to the website.
