### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by mocheaz** [cangelis/l4pdf#10]
I'm receiving this error after installing 0.12 on ubuntu 13.10:
PDF could not be created: "Segmentation fault (core dumped)\n"

It worked good with 0.11on ubuntu 12.04.

What's wrong?

**Comment by cangelis** [comment]
This must be caused by `wkhtmltopdf` executable. I think you should open an issue on [wkhtmltopdf Repo](https://github.com/wkhtmltopdf/wkhtmltopdf)

**Comment by cangelis** [comment]
I'm closing the issue since looks like there's nothing to do with php-side. Please reopen the issue if you think we have something we can do.
