### ISSUE TITLE
Embedding images

### ISSUE THREAD

**Issue by michaelaguiar** [cangelis/l4pdf#11]
I can't seem to add any <img> tags and have them display as the PDF.  The only way I was able to get images to show up, is to having a background-image set in a css file.  I can't even add a <style> tag to the template, for dynamic image paths

**Comment by cangelis** [comment]
Do you have any specific reason for not using `<img>` ? In addition, you need to use full path when you are dealing with files in your server.

**Comment by michaelaguiar** [comment]
For some reason it didn't show up, but yea the img tags didn't work.  I actually solved the problem though, was due to the Mac version of wkhtmltopdf, the linux version works great.
