### ISSUE TITLE
Configure wkhtmltopdf path in windows

### ISSUE THREAD

**Issue by dharmendrajadon** [cangelis/l4pdf#13]
How can I configure wkhtmltopdf path in windows. I have my wkhtmltopdf in C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe

It is showing error: PDF could not be created: "The system cannot find the path specified.\r\n"

**Comment by MakamuEvans** [comment]
did you solve this?

**Comment by wapnen** [comment]
?

**Comment by cangelis** [comment]
Better wrap the executable path with `"`.

`'executable' => '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"'`
