### ISSUE TITLE
How to configure the converter in laravel

### ISSUE THREAD

**Issue by MakamuEvans** [cangelis/l4pdf#14]
Hi, i see you have a good html to pdf converter here,but cant really use it with Laravel. i installit well, but on use iget :PDFException in PDF.php line 146: PDF could not be created: "The system cannot find the path specified.\r\n" how so i configure executable path, and how doi even install it....no tutorial for this. Please Help. makamuevans@gmail.com

**Comment by cangelis** [comment]
#13
