### ISSUE TITLE
Overprinting

### ISSUE THREAD

**Issue by petercoles** [cangelis/l4pdf#8]
If the class is called several times using the Laravel facade (e.g. PDF::loadView(...)) in order to print different PDFs, each PDF generated also contains the content from the previous ones (e.g. when printing several invoices in a single run, invoice 1 is fine, invoice 2 is a composite of 1 and 2, invoice 2 is a composite of 1,2 and 3).

The problem is that the $htmlContent attribute isn't cleared between calls to generatePDF().

There are at least two possible ways to handle this (which is why this isn't a pull request!) You could:
1. reverse my earlier suggestion that allowed loadView() to concatenate new content to the end of htmlContent, so that it reverts to overwriting it instead.
2. extend the process that removes temporary files to also reset the html content accumulated during their preparation.

There are probably others too.

**Comment by cangelis** [comment]
removed the view concetenating and increased the version to `1.2.x` to avoid BC breaks.
