### ISSUE TITLE
Header with hebrew

### ISSUE THREAD

**Issue by mocheaz** [cangelis/l4pdf#9]
I'm trying to add a header with hebrew characters with headerCenter() method but the results is gibrish.
I was trying also with encoding('UTF-8') without success.

**Comment by cangelis** [comment]
Can you please show your html and run `wkhtmltopdf --version` to show us the version you're using? 

You may be missing 

```
<meta charset="utf-8">
```

**Comment by mocheaz** [comment]
wkhtmltopdf 0.10.0 rc2
no i'm not missing the meta tag, and the whole file is ok just the hader is not working.

**Comment by cangelis** [comment]
Are you sure the font you're using on the header supports hebrew? You may need to specify a font that supports hebrew using `headerFontName('FontName')` method.

If this can't resolve your issue, can you show us your code?

**Comment by mocheaz** [comment]
I tried with arial (is always work with hebrew)
Here my code;

``` php
$variables = compact('sale', 'items', 'lists', 'totals', 'failed_cc', 'footer_message');
$header = '[text in hebrew]';
$file_name = '[name of file]';
return PDF::loadView('reports.site_sale_summary', $variables)
            ->pageSize('A4')
            ->headerLine()
            ->disableJavascript()
            ->headerCenter('[page]/[topage]')
            ->headerFontName('arial')
            ->headerLeft($header)
            ->download($file_name);
}
```

**Comment by cangelis** [comment]
I just tried using some characters, and it works fine on me.

![screen shot 2014-02-18 at 16 49 46](https://f.cloud.github.com/assets/1162691/2196232/f92ac4d4-98ab-11e3-95d0-1f422a17d5c2.png)

version: `wkhtmltopdf 0.10.0 rc2`
code:

```
return PDF::loadView('hello')->headerCenter('v ɣ ð x f θ "ʕ-b-r" עבר בְרִית')->stream('test.pdf');
```

Make sure the data comes from the source is correct.

**Comment by mocheaz** [comment]
Weird...
I copied your header code
![screenshot 2014-02-18 17 01 15](https://f.cloud.github.com/assets/327305/2196337/cf7b8a2c-98ad-11e3-9d5b-c66eafd34e2b.png)
As you see the text in the page is good but just the header text is messing...

Any other idea?

**Comment by cangelis** [comment]
Interesting. I completely don't know what's going on. You can report the issue to the [wkhtmltopdf's repo](https://github.com/wkhtmltopdf/wkhtmltopdf).

Finally, you may take a look at [this link](http://www.gogolek.co.uk/blog/2012/08/wkhtmltopdf-non-lating-alphabet/).

**Comment by cangelis** [comment]
I am closing this issue since looks like there is nothing to do with php-side. If you still encounter this issue please report this to the wkhtmltopdf's repo.
